/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IntClienteSerPedidos.h"
#include "IntSerPedidosSerDisplay.h"
#include "IntCocineroSerPedidos.h"
#include <stdbool.h>
#include <string.h>


int cantidadUsuariosFila = 0;
cocinero vectorCocineros[3];
nodo_hamburguesa filaVirtual[10];
int cocinerosEnLinea[3] = {0,0,0};

int consultarNumeroCocineroDispobible()
{
	int i;
	for(i = 0; i < 3; i++)
	{
		if(vectorCocineros[i].ocupado == false)
		{
			return i;
		}
	}
	return -1;
}
void notificar_cocineros_1()
{
	CLIENT *datosConexion;
	void  *result_1;
	char ipServidor[10];
	notificacion  objNotificacion;
	strcpy(ipServidor,"localhost");

#ifndef	DEBUG
	datosConexion = clnt_create (ipServidor, notificar_cocineros, notificar_cocineros_version, "udp");
	if (datosConexion == NULL) {
		clnt_pcreateerror (ipServidor);
		exit (1);
	}
#endif	/* DEBUG */
	for(int i =0;i < 3;i++){
		objNotificacion.cocineros[i].noCocinero = vectorCocineros[i].noCocinero;
		objNotificacion.cocineros[i].ocupado = vectorCocineros[i].ocupado;
		objNotificacion.cocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra = vectorCocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra;
		strcpy(objNotificacion.cocineros[i].objHamburguesaAPreparar.nombreHamburguesa, vectorCocineros[i].objHamburguesaAPreparar.nombreHamburguesa);
		objNotificacion.cocineros[i].objHamburguesaAPreparar.tipoHamburguesa = vectorCocineros[i].objHamburguesaAPreparar.tipoHamburguesa;
	}
	objNotificacion.cantidadUsuariosFilaVirtual = cantidadUsuariosFila;
	//Enviar la notificación
	result_1 = enviarnotificacion_1(&objNotificacion, datosConexion);
	if (result_1 == (void *) NULL) {
		clnt_perror (datosConexion, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (datosConexion);
#endif	 /* DEBUG */
}

int * generarturno_1_svc(nodo_hamburguesa *argp, struct svc_req *rqstp)
{
	static int  result;
	int posicion = consultarNumeroCocineroDispobible();
	printf("\n\n Hamburguesa a preparar");
	printf("\n Nombre hamburguesa: %s", (*argp).nombreHamburguesa);
	printf("\n Tipo de hamburguesa: %d", (*argp).tipoHamburguesa);
	printf("\n Cantidad de ingredientes extra: %d", (*argp).cantidadIngredientesExtra);
	if(posicion==-1){
		printf("\n No hay cocineros disponibles");
		//Se asgina la hamburguesa pedida a la fila virtual
		filaVirtual[cantidadUsuariosFila] = *argp;
		cantidadUsuariosFila++;
		printf("\n Hamburguesa agregada a la fila virtual");
	}
	else{
		printf("\n El cocinero en la posicion %d está libre y se asiganara a la hamburguesa con nombre %s", (posicion+1), (*argp).nombreHamburguesa);
		//Se asgina la hamburguesa pedida al cocinero y se marca como ocupado
		vectorCocineros[posicion].ocupado = true;
		vectorCocineros[posicion].objHamburguesaAPreparar = *argp;
		printf("\n Hamburguesa asignada al cocinero");
	}
	result = cantidadUsuariosFila;
	notificar_cocineros_1();
	printf("\n");
	return &result;
}
int * seleccionaridcocinero_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int indexCoc= (*argp)-1;
	printf("> Validando cocinero %d\n", indexCoc+1);

	//1. Validamos que sea un codigo valido
	if(indexCoc<0 || indexCoc>3){
		result = 0;
		return &result;
	}

	//2. Validamos que ya no este conectado

	if( cocinerosEnLinea[indexCoc] != 0){
		result = 0;
		return &result;
	}
	
	//Pre. El cocinero no esta conectado y el codigo es valido 
	//3. Guardamos su conexion

	cocinerosEnLinea[indexCoc] = 1;

	//4. Notificamos la conexion
	result = 1;

	return &result;
}

int * terminarprepararpedido_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int indexCoc = (*argp)-1;
	printf("> Terminando pedido del cocinero %d\n", indexCoc+1);


	//1. Validar si el cocinero tiene un pedido
	if(!vectorCocineros[indexCoc].ocupado){
		result = 0;
		return &result;
	}
	
	//2. Se le asigna otro pedido al cocinero si hay pedidos en la fila
	// - Si no hay mas en la fila, el cocinero queda libre
	// - Si se atiende de la fila se debe mermar la cantidad de usuarios en la fila
	
	//Validacion si no hay fila
	if(cantidadUsuariosFila==0){
		vectorCocineros[indexCoc].ocupado=false;
		notificar_cocineros_1();
		result = 0;
		return &result;
	}
	//pre. Hay usuarios en la fila
	
	//Asignamos al cocinero el siguiente pedido
	vectorCocineros[indexCoc].objHamburguesaAPreparar=filaVirtual[0];
	//Movemos la fila
	for(int i=0;i<cantidadUsuariosFila-1;i++)
		filaVirtual[i]=filaVirtual[i+1];
	//Mermamos la fila
	cantidadUsuariosFila--;

	//3. Se debe notificar la actualizacion
	notificar_cocineros_1();
	result = 1;
	return &result;
}