/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IntCocineroSerPedidos.h"

void mostrarMenuCocinero(int *idCocinero, CLIENT *clnt){
	int opcion;
	do{	
		bool_t  *result_2;
		printf("\nCocinero No:%d",idCocinero);
		printf("\n1. Terminar preparar pedido");
		printf("\n2. Salir");
		printf("\nIngrese opcion: ");
		scanf("%d", &opcion);
		switch(opcion){
			case 1:{
				result_2 = terminarprepararpedido_1(idCocinero, clnt);
				if(result_2 == (bool_t *) NULL){
					clnt_perror(clnt, "call failed");
				}else if(*result_2 == 1){
					printf("\nPedido terminado con exito");
				}
				else{
					printf("\nNo hay pedidos pendientes");
				}
				break;
			}
			case 2:{
				printf("Hasta pronto\n");
				break;
			}
			default:{
				printf("Opcion incorrecta\n");
			}
		}
	}while(opcion!=2);
}
void
gestionar_cocineros_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	int  idCocinero;	

#ifndef	DEBUG
	clnt = clnt_create (host, gestionar_cocineros, gestionar_cocineros_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int opcion;
	do{
		printf("\n============ Menu ==============");
		printf("\n1. Seleccionar ID Cocinero");
		printf("\n2. Salir");
		printf("\n================================");
		printf("\nIngrese opcion: ");
		scanf("%d", &opcion);
		switch(opcion){
			case 1:{
				printf("\nDigite el ID del cocinero: ");
				scanf("%d", &idCocinero);
				result_1 = seleccionaridcocinero_1(&idCocinero, clnt);
				if(result_1 == (bool_t *) NULL){
					clnt_perror(clnt, "call failed");
					break;
				}
				else if (*result_1 == 1){
					printf("\nCocinero seleccionado con exito");
					mostrarMenuCocinero(&idCocinero,clnt);
				}	
				else{
					printf("\nCocinero no disponible");
				}			
				break;
			}

			case 2:{
				printf("Hasta pronto\n");
				break;
			}
			default:{
				printf("Opcion incorrecta\n");
			}
			
		}

	}while (opcion!=2);	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestionar_cocineros_1 (host);
exit (0);
}
