/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTCOCINEROSERPEDIDOS_H_RPCGEN
#define _INTCOCINEROSERPEDIDOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define gestionar_cocineros 0x20000003
#define gestionar_cocineros_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define seleccionarIDCocinero 1
extern  int * seleccionaridcocinero_1(int *, CLIENT *);
extern  int * seleccionaridcocinero_1_svc(int *, struct svc_req *);
#define terminarPrepararPedido 2
extern  int * terminarprepararpedido_1(int *, CLIENT *);
extern  int * terminarprepararpedido_1_svc(int *, struct svc_req *);
extern int gestionar_cocineros_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define seleccionarIDCocinero 1
extern  int * seleccionaridcocinero_1();
extern  int * seleccionaridcocinero_1_svc();
#define terminarPrepararPedido 2
extern  int * terminarprepararpedido_1();
extern  int * terminarprepararpedido_1_svc();
extern int gestionar_cocineros_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTCOCINEROSERPEDIDOS_H_RPCGEN */
